export enum PermissionModule {
  LIVESTOCK = "LIVESTOCK",
  CROPS = "CROPS",
  EQUIPMENT = "EQUIPMENT",
  FINANCE = "FINANCE",
  REPORTS = "REPORTS",
  SETTINGS = "SETTINGS",
  MARKETPLACE = "MARKETPLACE",
}

export enum PermissionAction {
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LISTING = "LISTING",
}
